# ----------------------------------------------------
# This file is generated by the vscode-qtdao.
# Don't modify this file!
# ----------------------------------------------------

list(APPEND ENTITY_FILE_LIST
    ${CMAKE_CURRENT_LIST_DIR}/sqliteentityinclude.h
    ${CMAKE_CURRENT_LIST_DIR}/sqliteentityinclude.cpp

    ${CMAKE_CURRENT_LIST_DIR}/viewcenter.h
    ${CMAKE_CURRENT_LIST_DIR}/viewcenter.cpp
)