# ----------------------------------------------------
# This file is generated by the vscode-qtdao.
# Don't modify this file!
# ----------------------------------------------------

HEADERS += \
    ./viewcenter.h \
    ./sqliteentityinclude.h

SOURCES += \
    ./viewcenter.cpp \
    ./sqliteentityinclude.cpp

