/********************************************************************************
** This file is auto generated by vscode-qtdao.
** Don't modify this file!
********************************************************************************/
#include "sqliteentityinclude.h"
#include "viewcenter.h"

QTDAO_USING_NAMESPACE

static int id = ConfigSelector::registerConfig("sqlite_", new EntityDelegate_D9BE5DC7C924);

void EntityDelegate_D9BE5DC7C924::createEntityTables(dao::ConfigBuilder* config) {
    config->getClient()->createTable<(int)ConfigType::Sqlite, ViewCenter>();
}

void EntityDelegate_D9BE5DC7C924::entityTablesUpgrade(dao::ConfigBuilder* config, int oldVer, int newVer) {
    config->getClient()->tableUpgrade<(int)ConfigType::Sqlite, ViewCenter>(oldVer, newVer);
}